---
include:
  - board: eyelash_sofle_left
    shield: nice_epaper
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    #cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_sofle_right
    shield: nice_epaper
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: eyelash_sofle_dongle
    shield: eyelash_sofle_dongle


  - board: eyelash_sofle_left
    shield: settings_reset
