---
include:
  - board: eyelash_sofle_left
    shield: nice_oled
    snippet: studio-rpc-usb-uart
    #cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_sofle_right
    shield: nice_oled
  - board: eyelash_sofle_left
    shield: settings_reset
