manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      # Additional modules containing boards/shields/custom code can be listed here as well.
      # See:
      # - https://zmk.dev/docs/features/modules
      # - https://docs.zephyrproject.org/3.5.0/develop/west/manifest.html#projects
      # - name: m165437 #new entry
      # url-base: https://github.com/M165437 #new entry
    #- name: gpeye                         #ForRightSide
    #  url-base: https://github.com/GPeye  #ForRightSide
    - name: drMikeMiles                         #Mikey
      url-base: https://github.com/drMikeMiles  #Mikey
  projects:
    - name: eyelash_sofle
      url: https://github.com/a741725193/zmk-sofle
      revision: refactor
    - name: nice-view-gem #new entry
      remote: m165437 #new entry
      revision: main #new entry
   # - name: hammerbeam-slideshow          #ForRightSide
   #   remote: gpeye                       #ForRightSide
   #   revision: main                      #ForRightSide
    - name: Shield                         #Mikey
      remote: drMikeMiles                  #Mikey
      revision: main                       #Mikey
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
